services:
  macro_api:
    build: .
    container_name: macro_insights_api
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: macro-frontend
    ports:
      - "8501:8501"
    depends_on:
      - macro_api
    restart: unless-stopped

